theme = "kanagawa_custom"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[keys.insert]
"C-[" = "normal_mode"
"C-c" = "normal_mode"

[keys.select]
"C-[" = "normal_mode"
"C-c" = "normal_mode"
"C-s" = "split_selection_on_newline"

[keys.normal]
"C-n" = "repeat_last_motion"
"C-p" = "flip_selections"
"'" = "save_selection"

[keys.normal.space]
"u" = "switch_to_lowercase"
"U" = "switch_to_uppercase"

[editor.indent-guides]
render = true
indent-style = 4

[editor.file-picker]
hidden = false

