theme = "kanagawa"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[keys.insert]
"C-[" = "normal_mode"
"C-c" = "normal_mode"

[keys.select]
"C-[" = "normal_mode"
"C-c" = "normal_mode"

[keys.normal]
"C-l" = "@<A-.>"
"'" = "save_selection"

[editor.indent-guides]
render = true
indent-style = 4

[editor.file-picker]
hidden = false

