theme = "night_owl"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[keys.normal]
"space" = { f = { h = "symbol_picker" } }
"space" = { f = { j = "file_picker" } }
"space" = { f = { k = "diagnostics_picker" } }
"space" = { f = { b = "command_pallete" } }
"space" = { f = { y = "buffer_picker" } }
"space" = { f = { u = "buffer_picker" } }

[keys.insert]
"C-[" = "normal_mode"

[keys.select]
"C-[" = "normal_mode"

[editor.indent-guides]
render = true
indent-style = 4

[editor.file-picker]
hidden = false

