theme = "night_owl"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[keys.normal.space.f]
h = "symbol_picker"
j = "file_picker"
l = "diagnostics_picker"
b = "command_palette"
m = "buffer_picker"

[keys.insert]
"C-[" = "normal_mode"

[keys.select]
"C-[" = "normal_mode"

[editor.indent-guides]
render = true
indent-style = 4

[editor.file-picker]
hidden = false

