[[language]]
name = "python"
file-types = ["py","pyi","py3","pyw",".pythonstartup",".pythonrc"]
roots = [".", "pyproject.toml", "pyrightconfig.json"]
language-servers = ["pyright"]
shebangs = ["python"]
indent = { tab-width = 4, unit = "    " }

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
reportMissingTypeStubs = false

[[language]]
name = "php"
auto-format = false
language-servers = [ "scls", "intelephense" ] #, "typescript-language-server", "vscode-html-language-server"]
indent = { tab-width = 4, unit = "    " }

[language-server.intelephense.config]
environment = { phpVersion = "8.3.0" }
format = { braces = "k&r" }
telemetry = { enabled = false }
diagnostics = { relaxedTypeCheck = false, undefinedConstants = false, noMixedTypeCheck = false }
# stubs = [
#     # Defaults
#     "apache","bcmath","bz2","calendar","com_dotnet","Core","ctype","curl","date",
#     "dba","dom","enchant","exif","FFI","fileinfo","filter","fpm","ftp","gd",
#     "gettext","gmp","hash","iconv","imap","intl","json","ldap","libxml",
#     "mbstring","meta","mysqli","oci8","odbc","openssl","pcntl","pcre",
#     "PDO","pdo_ibm","pdo_mysql","pdo_pgsql","pdo_sqlite","pgsql","Phar",
#     "posix","pspell","readline","Reflection","session","shmop","SimpleXML",
#     "snmp","soap","sockets","sodium","SPL","sqlite3","standard","superglobals",
#     "sysvmsg","sysvsem","sysvshm","tidy","tokenizer","xml","xmlreader","xmlrpc",
#     "xmlwriter","xsl","Zend OPcache","zip","zlib",

#     # Custom
#     "/home/marco/php-stubs",
# ]


[[language]]
name = "javascript"
auto-format = false
language-servers = [ "scls", "typescript-language-server" ]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "html"
auto-format = false
language-servers = [ "scls", "typescript-language-server", "vscode-html-language-server" ]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "css"
auto-format = false
language-servers = [ "scls", "vscode-css-language-server" ]
indent = { tab-width = 4, unit = "    " }

[language-server.typescript-language-server]
command = "vtsls"
args = ["--stdio"]
config.hostInfo = "helix"

[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
feature_words = true
feature_snippets = true
snippets_first = true
snippets_inline_by_word_tail = false
feature_unicode_input = false
feature_paths = false
feature_citations = false
